from typing import Any, Protocol

from pydantic import BaseModel, Field

SAFETY_CONSTRAINTS = [
    "The copilot is control-plane only and cannot apply active rules.",
    "Any generated rule JSON must validate before a dry-run is produced.",
    "Sensitive-route changes still require the existing approval workflow.",
    "Do not put model calls in the request enforcement path.",
]


class PolicyCopilotRequest(BaseModel):
    prompt: str = Field(..., min_length=1, max_length=2_000)
    proposed_rules: dict[str, Any] | None = None


class PolicyCopilotInput(BaseModel):
    prompt: str
    active_rules: dict[str, Any]
    feature_summary: dict[str, Any]
    recommendations: dict[str, Any]
    anomalies: dict[str, Any]
    safety_constraints: list[str]


class PolicyCopilotResult(BaseModel):
    explanation: str
    proposed_rules: dict[str, Any] | None = None
    warnings: list[str] = Field(default_factory=list)


class PolicyCopilotAdapter(Protocol):
    provider: str

    def generate(self, copilot_input: PolicyCopilotInput) -> PolicyCopilotResult:
        ...


class CopilotConfigurationError(ValueError):
    pass


class FakePolicyCopilotAdapter:
    provider = "fake"

    def __init__(self, proposed_rules: dict[str, Any] | None = None):
        self.proposed_rules = proposed_rules

    def generate(self, copilot_input: PolicyCopilotInput) -> PolicyCopilotResult:
        route_count = len(copilot_input.active_rules.get("routes", {}))
        finding_count = int(copilot_input.anomalies.get("count") or 0)
        recommendation_count = len(copilot_input.recommendations.get("items", []))
        warnings = []
        if self.proposed_rules is None:
            warnings.append("No policy JSON was generated by the fake adapter.")

        return PolicyCopilotResult(
            explanation=(
                "Fake copilot analyzed "
                f"{route_count} active routes, {recommendation_count} recommendations, "
                f"and {finding_count} anomaly findings for prompt: {copilot_input.prompt}"
            ),
            proposed_rules=self.proposed_rules,
            warnings=warnings,
        )


def get_policy_copilot_adapter(
    *,
    enabled: bool,
    provider: str,
    proposed_rules: dict[str, Any] | None = None,
) -> PolicyCopilotAdapter:
    if not enabled:
        raise CopilotConfigurationError("AI policy copilot is disabled")

    normalized_provider = provider.strip().lower()
    if normalized_provider == "fake":
        return FakePolicyCopilotAdapter(proposed_rules=proposed_rules)

    raise CopilotConfigurationError(
        f"AI policy copilot provider is not configured: {provider}"
    )


def build_copilot_input(
    request: PolicyCopilotRequest,
    *,
    active_rules: dict[str, Any],
    feature_summary: dict[str, Any],
    recommendations: dict[str, Any],
    anomalies: dict[str, Any],
) -> PolicyCopilotInput:
    return PolicyCopilotInput(
        prompt=request.prompt,
        active_rules=active_rules,
        feature_summary=feature_summary,
        recommendations=recommendations,
        anomalies=anomalies,
        safety_constraints=SAFETY_CONSTRAINTS,
    )
